# Generated by Django 4.2.27 on 2026-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='添付ファイル'),
        ),
    ]
