# Generated by Django 4.2.27 on 2025-12-07 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_tasks', to=settings.AUTH_USER_MODEL, verbose_name='参加者'),
        ),
    ]
