# Generated by Django 4.2.27 on 2026-01-30 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskassignment_joined_at_taskassignment_role_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimepassword',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='message_type',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(default='todo', max_length=20),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='メイン', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='tasks.task')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='assigned_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.chatthread'),
        ),
    ]
