# Generated by Django 4.2.27 on 2025-12-07 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
