# Generated by Django 4.2.27 on 2025-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_mode',
            field=models.CharField(choices=[('none', '繰り返しなし'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], default='none', max_length=10, verbose_name='繰り返し設定'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
