# Generated by Django 4.2.27 on 2025-12-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
